version: "2.1"
services:

  api:
    container_name: books_api
    build: .
    ports:
      - "5001:5000"
    volumes: 
      - ./src:/app:rw
    links:
      - mysql
    depends_on: 
      mysql:
        condition: service_healthy
  mysql:
    container_name: books_db
    image: mysql:5.6
    environment: 
      - MYSQL_ROOT_PASSWORD=pass
    volumes: 
      - ./data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

#volumes: 
#  books:
