version: "2.1"
services:

  api:
    container_name: books_api
    build: .
    ports:
      - "5001:5000"
    volumes: 
      - ./src:/app:rw
    links:
      - mysql
    depends_on: 
      mysql:
        condition: service_healthy
    restart: always

  frontend:
    container_name: books_frontend
    build: ./frontend
    volumes: 
      - ./frontend/src:/app
    ports: 
      - "3000:3000"

  mysql:
    container_name: books_db
    image: mysql:5.6
    environment: 
      - MYSQL_ROOT_PASSWORD=pass
    volumes: 
      - ./data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 3s
      retries: 50

#volumes: 
#  books:
